name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS via SSH & Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with SCP
        run: |
          scp -i ~/.ssh/id_rsa -r ./build ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/meddoc-react

      - name: Restart Docker container (optional)
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          docker stop meddoc-container || true
          docker rm meddoc-container || true
          docker run -d -p 3000:80 --name meddoc-container -v /var/www/meddoc-react/build:/usr/share/nginx/html nginx
          EOF
